<a href="https://colab.research.google.com/github/Latamila/Latamila/blob/main/anatomiaRedeNeural.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook: ', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook:  3.10.12


In [2]:
!pip install -q -U watermark

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 17.5 MB/s eta 0:00:00


In [3]:
!pip install -q torch==1.13.0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 890.1/890.1 MB 1.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 849.3/849.3 kB 40.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.1/557.1 MB 2.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.1/317.1 MB 2.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.0/21.0 MB 61.3 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.0.2+cu118 requires torch==2.0.1, but you have torch 1.13.0 which is incompatible.
torchdata 0.6.1 requires torch==2.0.1, but you have torch 1.13.0 which is incompatible.
torchtext 0.15.2 requires torch==2.0.1, but you have torch 1.13.0 which is incompatible.
torchvision 0.15.2+cu118 requires torch==2.0.1, but you have torch 1.13.0 which is incompatible.


In [4]:
!pip install -q pytorch-lightning==1.8.3

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 798.9/798.9 kB 3.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 7.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 805.2/805.2 kB 8.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.3/88.3 kB 6.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 764.8/764.8 kB 9.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 763.4/763.4 kB 13.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 761.3/761.3 kB 15.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.6/731.6 kB 13.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.1/731.1 kB 16.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 729.2/729.2 kB 18.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 728.8/728.8 kB 21.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 519.2/519.2 kB 16.1 MB/s 

In [5]:
import gc
import types
import pkg_resources
import torch
import pytorch_lightning as pl
from torch import nn, optim
from torch.autograd import Variable
from torch.utils.data import DataLoader
from pytorch_lightning.callbacks import ModelCheckpoint
from pytorch_lightning.utilities.types import TRAIN_DATALOADERS
import warnings
warnings.filterwarnings("ignore")

In [6]:
%reload_ext watermark
%watermark -a 'Data Science Camila' --iversions

Author: Data Science Camila

pytorch_lightning: 1.8.3
torch            : 1.13.0



**Verificando o ambiente de desenvolvimento**

In [7]:
processing_device = "cuda" if torch.cuda.is_available() else "cpu"

In [8]:
print(processing_device)

cpu


In [9]:
#verificando se GPU pode ser usada
torch_aval = torch.cuda.is_available()

In [10]:
print(torch_aval)

False


In [11]:
#labels para relatorio de verificação
lable_1 = 'visao geral do ambiente'
lable_2 = 'se nvidia-smi nao for encontrado, entao CUDA nao esta disponivel'
lable_3 = 'fim de checagem'

In [12]:
#funcaoo para verificar o que esta importado nesta sessao
def get_imports():
  for name, val in globals().items():
    if isinstance(val, types.ModuleType):
      name = val.__name__.split(".")[0]

    elif isinstance(val, type):
      name = val.__module__.split(".")[0]

    poorly_named_packages = {"PIL": "Pillow", "sklearn":"scikit-learn"}

    if name in poorly_named_packages.keys():
      name = poorly_named_packages[name]

    yield name

In [13]:
#imports nesta sessao
imports = list(set(get_imports()))
print(imports)

['Out', '_i6', 'types', '_oh', '_iii', '_ih', '_exit_code', '_i13', '_i12', '___', '_i8', '__doc__', 'In', '__loader__', '_i9', 'python_version', '_i3', '_i7', '_i1', 'lable_3', 'gc', '_i5', 'exit', '_i11', 'pytorch_lightning', 'processing_device', 'warnings', 'builtins', 'pkg_resources', '_dh', '_i4', '__', '_', '__package__', 'torch_aval', '_i10', 'lable_1', 'TRAIN_DATALOADERS', '__name__', '_ii', 'get_imports', '_i2', '_i', 'lable_2', '__spec__', 'get_ipython', 'torch', 'quit']


In [14]:
#loop para verificar os requerimentos
requirements = []
for m in pkg_resources.working_set:
  if m.project_name in imports and m.project_name!="pip":
    requirements.append((m.project_name, m.version))

In [15]:
print(requirements)

[('torch', '2.0.1+cu118')]


In [16]:
pasta_dados = r'dados'

In [17]:
print(f'{lable_1:-^100}')
print()
print(f'Pasta de dados: ', requirements)
print(f'Versoes dos pacotes requeridos: ', requirements)
print(f'Dispositivo que sera usado para treinar o modelo: ', processing_device)
print(f'CUDA está disponivel?', torch_aval)
print('Versao do pytorch:', torch.__version__)
print('Versao do lightning: ', pl.__version__)
print()
print(f'{lable_2:-^100}')
!nvidia-smi
gc.collect()
print()
print(f'Limpando a Memoria da GPU(se dispnivel):', torch.cuda.empty_cache())
print(f'{lable_3:-^100}')

--------------------------------------visao geral do ambiente---------------------------------------

Pasta de dados:  [('torch', '2.0.1+cu118')]
Versoes dos pacotes requeridos:  [('torch', '2.0.1+cu118')]
Dispositivo que sera usado para treinar o modelo:  cpu
CUDA está disponivel? False
Versao do pytorch: 1.13.0+cu117
Versao do lightning:  1.8.3

------------------se nvidia-smi nao for encontrado, entao CUDA nao esta disponivel------------------
/bin/bash: line 1: nvidia-smi: command not found

Limpando a Memoria da GPU(se dispnivel): None
------------------------------------------fim de checagem-------------------------------------------


In [18]:
#dados de entrada
dados_entrada = [Variable(torch.Tensor([0,0])),
                 Variable(torch.Tensor([0,1])),
                 Variable(torch.Tensor([1,0])),
                 Variable(torch.Tensor([1,1]))]

In [19]:
#Dados de saida
dados_saida = [Variable(torch.Tensor([0])),
               Variable(torch.Tensor([1])),
               Variable(torch.Tensor([1])),
               Variable(torch.Tensor([0]))]

In [20]:
type(dados_entrada)

list

In [22]:
type(dados_saida)

list

In [23]:
dados_final = list(zip(dados_entrada, dados_saida))

In [24]:
dados_final

[(tensor([0., 0.]), tensor([0.])),
 (tensor([0., 1.]), tensor([1.])),
 (tensor([1., 0.]), tensor([1.])),
 (tensor([1., 1.]), tensor([0.]))]

In [25]:
type(dados_final)

list

In [26]:
loader_treinamento = DataLoader(dados_final, batch_size = 1)

In [27]:
type(loader_treinamento)

torch.utils.data.dataloader.DataLoader

In [28]:
class SimpleNet(pl.LightningModule):
  #metodo construtor
  #usado para inicializar os parametros do modelo
  def __init__(self):
    super(SimpleNet, self).__init__()

    self.input_layer = nn.Linear(2,4)
    self.output_layer = nn.Linear(4,1)
    self.sigmoid = nn.Sigmoid()
    self.loss = nn.MSELoss()
#metodo da passada para frente(forward)
  def forward(self, input):
    x = self.input_layer(input)
    x = self.sigmoid(x)
    output = self.output_layer(x)
    return output
#metodo de otimizacao
  def configure_optimizers(self):
    params = self.parameters()
    optimizer = optim.Adam(params = params, lr = 0.01)
    return optimizer
#metodo das passadas de treinamento
  def training_step(self, batch, batch_idx):
    entrada, saida = batch
    outputs = self(entrada)
    loss = self.loss(outputs, saida)
    return loss

**Compreendendo as dimensoes em nn.Linear   (2,4)

Especificação da função: torch.nn.Linear(in_features, out_features, bias=True)

in_features: tamanho da matriz dos dados de entrada. em nosso exemplo 2 x 4

out_features: tamanho da matriz dos dados de saida. em nosso exemplo valor 4 x 1.

bias: valor aditivo (padrao igual a True)

Para que a multiplicação de matrizes aconteça, usamos a primeira dimensão de input e a primeira dimensao de output. Em nosso exemplo 2 x 4.

Cada valor de entrada será multiplicado por um valor de peso e ao final o modelo aprende os valores ideais dos pesos que repressenta a relação entre dados de entrada e saida.

Observe que usamos batch_size igual a 1 e nesse caso cada registro é uma unidade, o que influencia na dimensão das matrizes dos dados.


In [29]:
#loop de treinamento
#cria o modelo
modelo = SimpleNet()

In [31]:
#cria o checkpoint pelo callback
checkpoint_callback = ModelCheckpoint()

In [32]:
#cria o trainer
trainer = pl.Trainer(devices = 1,
                     accelerator = 'cpu',
                     max_epochs = 100,
                     callbacks = [checkpoint_callback])

INFO:pytorch_lightning.utilities.rank_zero:GPU available: False, used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:IPU available: False, using: 0 IPUs
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs


In [33]:
trainer.fit(modelo, train_dataloaders = loader_treinamento)

INFO:pytorch_lightning.callbacks.model_summary:
  | Name         | Type    | Params
-----------------------------------------
0 | input_layer  | Linear  | 12    
1 | output_layer | Linear  | 5     
2 | sigmoid      | Sigmoid | 0     
3 | loss         | MSELoss | 0     
-----------------------------------------
17        Trainable params
0         Non-trainable params
17        Total params
0.000     Total estimated model params size (MB)


Training: 0it [00:00, ?it/s]

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=100` reached.


In [34]:
modelo.device

device(type='cpu')

In [35]:
modelo.eval()

SimpleNet(
  (input_layer): Linear(in_features=2, out_features=4, bias=True)
  (output_layer): Linear(in_features=4, out_features=1, bias=True)
  (sigmoid): Sigmoid()
  (loss): MSELoss()
)

In [36]:
modelo.state_dict()

OrderedDict([('input_layer.weight',
              tensor([[-0.4092,  0.2059],
                      [-0.1561,  0.1468],
                      [-0.3360, -0.6610],
                      [-0.1891,  0.6463]])),
             ('input_layer.bias',
              tensor([ 0.0058,  0.0424, -0.1355,  0.2356])),
             ('output_layer.weight',
              tensor([[ 0.5135, -0.1636, -0.2122, -0.1279]])),
             ('output_layer.bias', tensor([0.4918]))])

In [37]:
ls lightning_logs/*/

checkpoints/  hparams.yaml


**AVALIAÇÃO DO MODELO**

In [38]:
melhor_modelo = (checkpoint_callback.best_model_path)

In [39]:
print(melhor_modelo)

/content/lightning_logs/version_0/checkpoints/epoch=99-step=400.ckpt


In [40]:
modelo_final = modelo.load_from_checkpoint(checkpoint_callback.best_model_path)

In [41]:
modelo_final.state_dict()

OrderedDict([('input_layer.weight',
              tensor([[-0.4092,  0.2059],
                      [-0.1561,  0.1468],
                      [-0.3360, -0.6610],
                      [-0.1891,  0.6463]])),
             ('input_layer.bias',
              tensor([ 0.0058,  0.0424, -0.1355,  0.2356])),
             ('output_layer.weight',
              tensor([[ 0.5135, -0.1636, -0.2122, -0.1279]])),
             ('output_layer.bias', tensor([0.4918]))])

In [42]:
#novo registro de entrada
novo_dado_entrada_A = Variable(torch.Tensor([1,1]))


In [43]:
#faz a previsao
pred_A = modelo_final(novo_dado_entrada_A)

In [44]:
print(pred_A)

tensor([0.5032], grad_fn=<AddBackward0>)


In [45]:
print("A previsão de classe de pred_A é: ", int(pred_A.round()))

A previsão de classe de pred_A é:  1


In [46]:
#novos dados de entrada
novos_dados = [Variable(torch.Tensor([1,1])),
               Variable(torch.Tensor([0,0])),
               Variable(torch.Tensor([1,0])),
               Variable(torch.Tensor([0,1]))]

In [47]:
#loop de teste
for val in novos_dados:
  #faz a previsao de cada registro
  previsao = modelo_final(val)
  #imprime o resultado
  print([int(val[0]), int(val[1])], int(previsao.round()))

[1, 1] 1
[0, 0] 0
[1, 0] 0
[0, 1] 1


FIM
